import type { Metadata } from 'next';
import './globals.css';
import { Chakra_Petch } from 'next/font/google'

const chakraPetch = Chakra_Petch({
  weight: '400',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${chakraPetch.className}`}>
        {children}
        <canvas id='darkDithering' width='20px' height='20px' className='letsNotShowThis'/>
        <canvas id='lightDithering2' width='16px' height='16px' className='letsNotShowThis'/>
        <canvas id='lightDithering' width='16px' height='16px' className='letsNotShowThis'/>
        <canvas id='lines' width='20px' height='20px' className='letsNotShowThis'/>
      </body>
    </html>
  );
}
